# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /cdk # Location of package.json
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directory: /web # Location of Gemfile
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: / # Required for GitHub Actions, see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--
    schedule:
      interval: weekly
  - package-ecosystem: devcontainers
    directory: / # Required for Dev container features, see https://containers.dev/guide/dependabot
    schedule:
      interval: weekly
